ALTER TABLE vehicles
ADD COLUMN brand VARCHAR(100) NULL,
ADD COLUMN year INT NULL,
ADD COLUMN mileage INT NULL,
ADD COLUMN usage_hours INT NULL,
ADD COLUMN last_maintenance DATE NULL,
ADD COLUMN next_maintenance DATE NULL,
ADD COLUMN notes TEXT NULL,
ADD COLUMN last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP; 